/* ---- módulo integrado ---- */
(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`$${Number(n||0).toFixed(2)}`;
let db=null, empleados={}, marcaciones={}, ajustes={}, recibos={};
function iso(d){return d.toISOString().slice(0,10)}
function monthRange(){const d=new Date(),f=new Date(d.getFullYear(),d.getMonth(),1),t=new Date(d.getFullYear(),d.getMonth()+1,0);return[iso(f),iso(t)]}
function datesBetween(a,b){const out=[];if(!a||!b)return out;let d=new Date(a+'T12:00:00'),e=new Date(b+'T12:00:00');for(;d<=e;d.setDate(d.getDate()+1))out.push(iso(d));return out}
function ts(v){return Number(v?.timestamp||v?.ts||0)}
function hoursDay(x){if(!x)return 0;const en=ts(x.entrada),sa=ts(x.salida),as=ts(x.almuerzo_salida),ar=ts(x.almuerzo_regreso);if(!en||!sa||sa<=en)return 0;let h=(sa-en)/36e5;if(as&&ar&&ar>as)h-=(ar-as)/36e5;return Math.max(0,h)}
function hourly(emp){const s=Number(emp.salario||0),t=String(emp.tipoSalario||'diario').toLowerCase();if(t==='mensual')return s/(30*8);if(t==='quincenal')return s/(15*8);return s/8}
function basePeriod(emp,from,to){const rate=hourly(emp),days=datesBetween(from,to),work=days.reduce((n,d)=>n+hoursDay((marcaciones[emp.__id]||{})[d]),0),regular=Math.min(work,days.length*8),extra=Math.max(0,work-days.length*8);return {rate,days:days.length,work,regular,extra,base:regular*rate};}
function key(){return `${$('#payFrom')?.value||''}_${$('#payTo')?.value||''}`}
function mount(){const main=$('.pc-main'),attendance=$('#pc-attendance');if(!main||!attendance||$('#pc-payroll'))return;
 const page=document.createElement('section');page.id='pc-payroll';page.className='pc-page';page.innerHTML=`<div class="pc-page-title"><h2>Nómina y pagos</h2><p>Calcula salarios, horas extras, bonificaciones, descuentos y recibos.</p></div>
 <div class="pay-toolbar pc-card"><div><label>Desde</label><input type="date" id="payFrom"></div><div><label>Hasta</label><input type="date" id="payTo"></div><div><label>Funcionario</label><select id="payEmp"><option value="">Todos</option></select></div><div><label>Estado</label><select id="payStatus"><option value="">Todos</option><option value="pendiente">Pendiente</option><option value="pagado">Pagado</option></select></div><button id="payPreview">Calcular nómina</button></div>
 <div id="paySummary" class="pay-summary"></div><div id="payList" class="pay-list"></div>
 <div class="pay-actions"><button id="payExcel">📊 Exportar Excel</button><button id="payPdf">🧾 Recibo PDF seleccionado</button><button id="payPdfGeneral">📄 Resumen PDF general</button></div>
 <div class="pc-card pay-history-card"><div class="pc-page-title"><h3>Historial de pagos</h3><p>Consulta los períodos pagados sin modificar el historial de marcaciones.</p></div><div class="pay-toolbar"><div><label>Empleado</label><select id="payHistoryEmp"><option value="">Todos</option></select></div><button id="payHistoryRefresh" type="button">Actualizar historial</button></div><div id="payHistoryList" class="pay-list"></div></div>`;
 main.insertBefore(page,$('#pc-gps'));
 const nav=$('.pc-nav');const btn=document.createElement('button');btn.dataset.page='pc-payroll';btn.innerHTML='<span>💰</span>Nómina';nav.insertBefore(btn,[...nav.children].find(x=>x.dataset.page==='pc-gps'));
 btn.onclick=()=>{$$('.pc-nav button').forEach(x=>x.classList.toggle('active',x===btn));$$('.pc-page').forEach(p=>p.classList.toggle('active',p.id==='pc-payroll'));window.scrollTo({top:0,behavior:'smooth'});render()};
 const [f,t]=monthRange();$('#payFrom').value=f;$('#payTo').value=t;
 $('#payPreview').onclick=validateAndLoad;$('#payEmp').onchange=render;$('#payStatus').onchange=render;$('#payExcel').onclick=exportExcel;$('#payPdf').onclick=pdfSelected;$('#payPdfGeneral').onclick=pdfGeneral;$('#payHistoryEmp').onchange=renderHistory;$('#payHistoryRefresh').onclick=renderHistory;
 connect();
}
function connect(){if(!window.firebase?.apps?.length)return setTimeout(connect,250);db=firebase.database();window.PoladentData.subscribe('empleados',s=>{empleados=s.val()||{};window.PoladentPerformance?.schedule('nomina-empleados',()=>{fillEmployees();render()})});window.PoladentData.subscribe('marcaciones',s=>{marcaciones=s.val()||{};window.PoladentPerformance?.schedule('nomina-marcaciones',render)});window.PoladentData.subscribe('nomina_recibos',s=>{recibos=s.val()||{};window.PoladentPerformance?.schedule('nomina-recibos',renderHistory)});loadAdjustments()}
function fillEmployees(){const options='<option value="">Todos</option>'+Object.entries(empleados).sort((a,b)=>(a[1].nombre||'').localeCompare(b[1].nombre||'')).map(([id,e])=>`<option value="${id}">${esc(e.nombre||'Sin nombre')}</option>`).join('');['payEmp','payHistoryEmp'].forEach(id=>{const el=$('#'+id);if(!el)return;const val=el.value;el.innerHTML=options;el.value=val});renderHistory()}
function validPeriod(){const f=$('#payFrom')?.value,t=$('#payTo')?.value;if(!f||!t){alert('Selecciona las fechas desde y hasta.');return false}if(f>t){alert('La fecha Desde no puede ser posterior a Hasta.');return false}return true}
async function validateAndLoad(){if(validPeriod())await loadAdjustments()}
async function loadAdjustments(){if(!db||!validPeriod())return;const s=await db.ref(`nomina_ajustes/${key()}`).once('value');ajustes=s.val()||{};render()}
function rows(){const filter=$('#payEmp')?.value||'',status=$('#payStatus')?.value||'',from=$('#payFrom')?.value,to=$('#payTo')?.value;return Object.entries(empleados).filter(([id])=>!filter||id===filter).map(([id,e])=>{const emp={...e,__id:id},calc=basePeriod(emp,from,to),a=ajustes[id]||{},bonus=Number(a.bonificacion||0),ded=Number(a.descuento||0),extraRate=Number(a.valorHoraExtra||calc.rate*1.5),extraPay=calc.extra*extraRate,total=Math.max(0,calc.base+extraPay+bonus-ded),st=a.estado||'pendiente';return{id,emp,calc,a,bonus,ded,extraRate,extraPay,total,status:st}}).filter(r=>!status||r.status===status)}
function render(){if(!$('#payList'))return;const rs=rows(),total=rs.reduce((n,r)=>n+r.total,0),paid=rs.filter(r=>r.status==='pagado').reduce((n,r)=>n+r.total,0);$('#paySummary').innerHTML=`<div><small>Funcionarios</small><b>${rs.length}</b></div><div><small>Total nómina</small><b>${money(total)}</b></div><div><small>Pagado</small><b>${money(paid)}</b></div><div><small>Pendiente</small><b>${money(total-paid)}</b></div><div><small>Horas extra</small><b>${rs.reduce((n,r)=>n+r.calc.extra,0).toFixed(2)}</b></div>`;
 $('#payList').innerHTML=rs.length?rs.map(r=>`<article class="pay-card ${r.status==='pagado'?'paid':''}" data-id="${r.id}"><header><div><h3>${esc(r.emp.nombre||'Sin nombre')}</h3><span>${money(r.emp.salario)} · ${esc(r.emp.tipoSalario||'diario')}</span></div><label><input type="radio" name="paySelected" value="${r.id}"> Seleccionar</label></header><div class="pay-metrics"><span>Horas: <b>${r.calc.work.toFixed(2)}</b></span><span>Extra: <b>${r.calc.extra.toFixed(2)}</b></span><span>Base: <b>${money(r.calc.base)}</b></span><span>Total: <b>${money(r.total)}</b></span></div><div class="pay-fields"><label>Valor hora extra<input type="number" step="0.01" data-f="valorHoraExtra" value="${r.extraRate.toFixed(2)}"></label><label>Bonificación<input type="number" step="0.01" data-f="bonificacion" value="${r.bonus.toFixed(2)}"></label><label>Descuento<input type="number" step="0.01" data-f="descuento" value="${r.ded.toFixed(2)}"></label><label>Método<select data-f="metodo"><option ${r.a.metodo==='Efectivo'?'selected':''}>Efectivo</option><option ${r.a.metodo==='Transferencia'?'selected':''}>Transferencia</option><option ${r.a.metodo==='Pago móvil'?'selected':''}>Pago móvil</option><option ${r.a.metodo==='Otro'?'selected':''}>Otro</option></select></label><label class="pay-note">Observación<input data-f="nota" value="${esc(r.a.nota||'')}"></label></div><footer><button data-save>💾 Guardar ajustes</button><button data-paid>${r.status==='pagado'?'↩ Marcar pendiente':'✅ Marcar pagado'}</button><button data-receipt>🧾 Recibo PDF</button></footer></article>`).join(''):'<div class="pc-card">No hay funcionarios con esos filtros.</div>';
 $$('[data-save]','#payList').forEach(b=>b.onclick=()=>saveCard(b.closest('.pay-card'),false));$$('[data-paid]','#payList').forEach(b=>b.onclick=()=>saveCard(b.closest('.pay-card'),true));$$('[data-receipt]','#payList').forEach(b=>b.onclick=()=>makePdf(b.closest('.pay-card').dataset.id));}
async function saveCard(card,toggle){const id=card.dataset.id,current=ajustes[id]||{},data={...current};$$('[data-f]',card).forEach(x=>data[x.dataset.f]=x.value);data.bonificacion=Number(data.bonificacion||0);data.descuento=Number(data.descuento||0);data.valorHoraExtra=Number(data.valorHoraExtra||0);if(toggle)data.estado=(current.estado||'pendiente')==='pagado'?'pendiente':'pagado';data.actualizadoEn=Date.now();await db.ref(`nomina_ajustes/${key()}/${id}`).set(data);if(data.estado==='pagado'){const r=rows().find(x=>x.id===id);await db.ref(`nomina_recibos/${key()}/${id}`).set({...data,empleado:id,empleadoNombre:r?.emp?.nombre||empleados[id]?.nombre||'Empleado',periodo:key(),desde:$('#payFrom').value,hasta:$('#payTo').value,horasTrabajadas:Number(r?.calc?.work||0),horasExtra:Number(r?.calc?.extra||0),pagoBase:Number(r?.calc?.base||0),pagoExtra:Number(r?.extraPay||0),total:Number(r?.total||0),pagadoEn:Date.now()})}await loadAdjustments();renderHistory()}
function exportExcel(){const rs=rows();if(!rs.length)return alert('No hay nómina para exportar.');if(!window.XLSX)return alert('Excel todavía no cargó.');const data=rs.map(r=>({Empleado:r.emp.nombre,Periodo:`${$('#payFrom').value} al ${$('#payTo').value}`,Salario:r.emp.salario,Tipo:r.emp.tipoSalario,'Horas trabajadas':Number(r.calc.work.toFixed(2)),'Horas extra':Number(r.calc.extra.toFixed(2)),'Pago base':Number(r.calc.base.toFixed(2)),'Pago extra':Number(r.extraPay.toFixed(2)),Bonificación:r.bonus,Descuento:r.ded,Total:Number(r.total.toFixed(2)),Estado:r.status,Método:r.a.metodo||''}));const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(data);ws['!cols']=Object.keys(data[0]).map(k=>({wch:Math.max(13,k.length+3)}));XLSX.utils.book_append_sheet(wb,ws,'Nómina');XLSX.writeFile(wb,`Nomina_${$('#payFrom').value}_${$('#payTo').value}.xlsx`)}

function historyRows(){const empFilter=$('#payHistoryEmp')?.value||'',out=[];Object.entries(recibos||{}).forEach(([periodo,items])=>Object.entries(items||{}).forEach(([id,r])=>{if(empFilter&&id!==empFilter)return;out.push({...r,empleado:id,periodo:r.periodo||periodo})}));return out.sort((a,b)=>Number(b.pagadoEn||0)-Number(a.pagadoEn||0))}
function renderHistory(){const host=$('#payHistoryList');if(!host)return;const rs=historyRows();host.innerHTML=rs.length?rs.map(r=>`<article class="pay-card paid"><header><div><h3>${esc(r.empleadoNombre||empleados[r.empleado]?.nombre||'Empleado')}</h3><span>${esc(r.desde||'—')} al ${esc(r.hasta||'—')}</span></div><b>${money(r.total||0)}</b></header><div class="pay-metrics"><span>Horas: <b>${Number(r.horasTrabajadas||0).toFixed(2)}</b></span><span>Extra: <b>${Number(r.horasExtra||0).toFixed(2)}</b></span><span>Método: <b>${esc(r.metodo||'—')}</b></span><span>Pagado: <b>${r.pagadoEn?new Date(r.pagadoEn).toLocaleString('es-VE'):'—'}</b></span></div><footer><button type="button" data-hist-pdf data-periodo="${esc(r.periodo)}" data-emp="${esc(r.empleado)}">🧾 Descargar recibo</button></footer></article>`).join(''):'<div class="pc-card">Todavía no hay pagos registrados con este filtro.</div>';$$('[data-hist-pdf]',host).forEach(b=>b.onclick=()=>pdfHistory(b.dataset.periodo,b.dataset.emp))}
function pdfHistory(periodo,id){const r=recibos?.[periodo]?.[id];if(!r)return alert('No se encontró el recibo guardado.');if(!window.jspdf?.jsPDF)return alert('PDF todavía no cargó.');const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(18);doc.text('POLADENT CASA DENTAL',14,18);doc.setFontSize(14);doc.text('RECIBO DE PAGO',14,30);doc.setFontSize(10);let y=42;[['Funcionario',r.empleadoNombre||empleados[id]?.nombre||'Empleado'],['Periodo',`${r.desde||'—'} al ${r.hasta||'—'}`],['Horas trabajadas',Number(r.horasTrabajadas||0).toFixed(2)],['Horas extra',Number(r.horasExtra||0).toFixed(2)],['Pago base',money(r.pagoBase)],['Pago horas extra',money(r.pagoExtra)],['Bonificación',money(r.bonificacion)],['Descuento',money(r.descuento)],['TOTAL PAGADO',money(r.total)],['Método',r.metodo||'—'],['Observación',r.nota||'—'],['Fecha de pago',r.pagadoEn?new Date(r.pagadoEn).toLocaleString('es-VE'):'—']].forEach(([a,b])=>{doc.text(`${a}: ${b}`,14,y);y+=7});doc.save(`Recibo_${String(r.empleadoNombre||'empleado').replace(/\s+/g,'_')}_${r.desde||periodo}.pdf`)}
function pdfGeneral(){if(!validPeriod())return;const rs=rows();if(!rs.length)return alert('No hay nómina para generar.');if(!window.jspdf?.jsPDF)return alert('PDF todavía no cargó.');const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(17);doc.text('POLADENT CASA DENTAL',14,18);doc.setFontSize(13);doc.text(`RESUMEN DE NÓMINA · ${$('#payFrom').value} al ${$('#payTo').value}`,14,29);doc.setFontSize(9);let y=40;rs.forEach((r,i)=>{if(y>270){doc.addPage();y=20}doc.text(`${i+1}. ${r.emp.nombre||'Empleado'} · Horas ${r.calc.work.toFixed(2)} · Extra ${r.calc.extra.toFixed(2)} · Total ${money(r.total)} · ${r.status}`,14,y);y+=7});y+=5;doc.setFontSize(11);doc.text(`TOTAL GENERAL: ${money(rs.reduce((n,r)=>n+r.total,0))}`,14,y);doc.save(`Resumen_Nomina_${$('#payFrom').value}_${$('#payTo').value}.pdf`)}

function pdfSelected(){const id=$('input[name="paySelected"]:checked')?.value;if(!id)return alert('Selecciona un funcionario.');makePdf(id)}
function makePdf(id){const r=rows().find(x=>x.id===id)||(()=>{const e=empleados[id];if(!e)return null;return rows().find(x=>x.id===id)})();if(!r)return alert('No se encontró el funcionario.');if(!window.jspdf?.jsPDF)return alert('PDF todavía no cargó.');const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(18);doc.text('POLADENT CASA DENTAL',14,18);doc.setFontSize(14);doc.text('RECIBO DE PAGO',14,30);doc.setFontSize(10);let y=42;[['Funcionario',r.emp.nombre],['Periodo',`${$('#payFrom').value} al ${$('#payTo').value}`],['Salario',money(r.emp.salario)+' ('+(r.emp.tipoSalario||'diario')+')'],['Horas trabajadas',r.calc.work.toFixed(2)],['Horas extra',r.calc.extra.toFixed(2)],['Pago base',money(r.calc.base)],['Pago horas extra',money(r.extraPay)],['Bonificación',money(r.bonus)],['Descuento',money(r.ded)],['TOTAL A PAGAR',money(r.total)],['Estado',r.status],['Método',r.a.metodo||'—'],['Observación',r.a.nota||'—']].forEach(([a,b])=>{doc.text(`${a}: ${b}`,14,y);y+=7});y+=15;doc.line(20,y,90,y);doc.line(120,y,190,y);doc.text('Firma del funcionario',25,y+6);doc.text('Firma autorizada',135,y+6);doc.save(`Recibo_${String(r.emp.nombre||'empleado').replace(/\s+/g,'_')}_${$('#payFrom').value}.pdf`)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,400));else setTimeout(mount,400);
})();

