/* Empleado rápido: GPS multisede, cámara en vivo y control de dispositivo */
(function(){
  'use strict';
  const etapas=['entrada','almuerzo_salida','almuerzo_regreso','salida'];
  let empleadoActual=null,marcando=false,gpsConfig={activo:false,precisionMaxima:120,sedes:{}},segConfig={activo:true,fotoEntrada:true,fotoAlmuerzoSalida:false,fotoAlmuerzoRegreso:false,fotoSalida:true,alertarDispositivoCompartido:true,ventanaDispositivoMinutos:10,guardarEvidencia:true};
  const $=id=>document.getElementById(id), db=()=>firebase.database();
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn();
  const todayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  function msg(text,type=''){const el=$('fastMsg');if(el){el.className='fast-msg '+type;el.textContent=text;}}
  function setBusy(v){marcando=v;document.querySelectorAll('#fastButtons button').forEach(b=>b.disabled=v);}
  function updateClock(){const n=new Date();$('fastClock').textContent=n.toLocaleTimeString('es-VE',{hour:'2-digit',minute:'2-digit'});$('fastDate').textContent=n.toLocaleDateString('es-VE',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});}
  function waitFirebase(cb){let tries=0;const t=setInterval(()=>{tries++;if(window.firebase&&firebase.apps&&firebase.apps.length&&firebase.database){clearInterval(t);cb();}if(tries>80){clearInterval(t);msg('No se pudo conectar con Firebase. Revisa internet o config.js.','error');}},200);}
  async function buscarEmpleado(pin){const s=await db().ref('empleados').orderByChild('pin').equalTo(pin).once('value');if(!s.exists())return null;let out=null;s.forEach(x=>{if(!out)out={id:x.key,...(x.val()||{})};});return out;}
  function renderEmpleado(e){const box=$('fastEmployee'),photo=$('fastPhoto');if(!e){box.classList.add('hidden');$('fastButtons').classList.add('hidden');$('fastName').textContent='Empleado';photo.outerHTML='<div id="fastPhoto" class="photo-placeholder">👤</div>';return;}$('fastName').textContent=e.nombre||'Empleado';photo.outerHTML=e.foto?`<img id="fastPhoto" src="${e.foto}" alt="Foto de empleado">`:'<div id="fastPhoto" class="photo-placeholder">👤</div>';box.classList.remove('hidden');$('fastButtons').classList.remove('hidden');}
  let pinTimer=null,lastInvalid='';function onPinInput(){clearTimeout(pinTimer);const pin=$('fastPin').value.trim();if(!pin){empleadoActual=null;renderEmpleado(null);msg('Ingrese su PIN para comenzar.');return;}pinTimer=setTimeout(async()=>{try{const e=await buscarEmpleado(pin);if(!e){empleadoActual=null;renderEmpleado(null);msg('PIN no encontrado. Verifica e intenta de nuevo.','error');if(pin.length>=3&&pin!==lastInvalid){lastInvalid=pin;registrarAlerta({codigo:'PIN_INVALIDO',motivo:'Intento de marcación con PIN no reconocido',empleado:'No identificado'});}return;}lastInvalid='';empleadoActual=e;renderEmpleado(e);msg(gpsConfig.activo?'Empleado encontrado. La ubicación se verificará al marcar.':'Empleado encontrado. Seleccione la marcación.','ok');}catch(e){msg('Error buscando empleado. Revisa la conexión.','error');}},350);}
  function getGps(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GPS no disponible en este dispositivo.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,obtenido:Date.now()}),e=>reject(new Error(e.code===1?'Activa el permiso de ubicación para poder marcar.':'No se pudo obtener una ubicación precisa. Intenta nuevamente.')),{enableHighAccuracy:true,timeout:20000,maximumAge:0});});}
  function distance(a,b,c,d){const R=6371000,r=x=>x*Math.PI/180,dp=r(c-a),dl=r(d-b),q=Math.sin(dp/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}
  function validarSede(gps){if(!gpsConfig.activo)return {ok:true,sede:null,distancia:null};const max=Number(gpsConfig.precisionMaxima)||120;if(Number(gps.accuracy)>max)return {ok:false,error:`La precisión del GPS es de ${Math.round(gps.accuracy)} m. Necesitamos ${max} m o menos. Sal al exterior o acércate a una ventana.`};let sedes=Object.entries(gpsConfig.sedes||{}).filter(([,s])=>s&&s.activo!==false&&Number.isFinite(Number(s.lat))&&Number.isFinite(Number(s.lon)));if(!sedes.length)return {ok:false,error:'El administrador todavía no ha configurado locales autorizados.'};const permitidas=empleadoActual.sedesPermitidas||{};if(!Object.keys(permitidas).length)return {ok:false,codigo:'SIN_SEDE',error:'Todavía no estás agregado a ninguna tienda oficial. Comunícate con el administrador.'};sedes=sedes.filter(([id])=>permitidas[id]);if(!sedes.length)return {ok:false,codigo:'SEDE_INACTIVA',error:'La tienda que tienes asignada no está activa. Comunícate con el administrador.'};const medidas=sedes.map(([id,s])=>({id,s,distancia:distance(gps.lat,gps.lon,Number(s.lat),Number(s.lon))})).sort((a,b)=>a.distancia-b.distancia);const best=medidas[0],radio=Number(best.s.radio)||Number(gpsConfig.radioDefault)||80;if(best.distancia>radio)return {ok:false,codigo:'FUERA_AREA',sedeCercana:best.s.nombre,distancia:best.distancia,radio,error:`Estás fuera del área autorizada. Local más cercano: ${best.s.nombre} a ${Math.round(best.distancia)} m; límite ${radio} m.`};return {ok:true,sede:{id:best.id,nombre:best.s.nombre,direccion:best.s.direccion||'',radio},distancia:best.distancia};}
  function deviceId(){let id=localStorage.getItem('poladent_device_id');if(!id){id=(crypto.randomUUID?crypto.randomUUID():'dev-'+Date.now()+'-'+Math.random().toString(36).slice(2));localStorage.setItem('poladent_device_id',id);}return id;}
  function requiresPhoto(tipo){if(segConfig.activo===false)return false;const per=empleadoActual?.seguridadFotos||{};const key={entrada:'fotoEntrada',almuerzo_salida:'fotoAlmuerzoSalida',almuerzo_regreso:'fotoAlmuerzoRegreso',salida:'fotoSalida'}[tipo];return per[key]!==undefined?!!per[key]:!!segConfig[key];}
  function ensureCameraUi(){if($('cameraOverlay'))return;document.body.insertAdjacentHTML('beforeend',`<div id="cameraOverlay" class="camera-overlay hidden"><div class="camera-dialog"><h3>Verificación de identidad</h3><p>Mira de frente a la cámara para registrar la marcación.</p><div class="camera-frame"><video id="cameraVideo" autoplay playsinline muted></video><img id="cameraPreview" class="hidden" alt="Foto capturada"></div><div class="camera-actions"><button id="cameraCapture" class="camera-primary">Tomar fotografía</button><button id="cameraRetry" class="camera-secondary hidden">Repetir</button><button id="cameraConfirm" class="camera-primary hidden">Usar fotografía</button><button id="cameraCancel" class="camera-danger">Cancelar</button></div><div id="cameraStatus" class="camera-status">La fotografía debe tomarse ahora; no se permite seleccionar desde la galería.</div><p class="privacy-note">La imagen se guarda únicamente como evidencia de asistencia para el administrador.</p></div></div>`);}
  function capturePhoto(){return new Promise(async(resolve,reject)=>{ensureCameraUi();const overlay=$('cameraOverlay'),video=$('cameraVideo'),preview=$('cameraPreview'),capture=$('cameraCapture'),retry=$('cameraRetry'),confirm=$('cameraConfirm'),cancel=$('cameraCancel'),status=$('cameraStatus');let stream=null,data=null;const close=()=>{stream?.getTracks().forEach(t=>t.stop());overlay.classList.add('hidden');};try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:960}},audio:false});video.srcObject=stream;overlay.classList.remove('hidden');video.classList.remove('hidden');preview.classList.add('hidden');capture.classList.remove('hidden');retry.classList.add('hidden');confirm.classList.add('hidden');status.textContent='Ubica tu rostro dentro de la cámara y pulsa “Tomar fotografía”.';capture.onclick=()=>{const canvas=document.createElement('canvas'),max=480,ratio=video.videoHeight/video.videoWidth||4/3;canvas.width=max;canvas.height=Math.round(max*ratio);const ctx=canvas.getContext('2d');ctx.translate(canvas.width,0);ctx.scale(-1,1);ctx.drawImage(video,0,0,canvas.width,canvas.height);data=canvas.toDataURL('image/jpeg',0.62);preview.src=data;video.classList.add('hidden');preview.classList.remove('hidden');capture.classList.add('hidden');retry.classList.remove('hidden');confirm.classList.remove('hidden');status.textContent='Revisa la fotografía antes de continuar.';};retry.onclick=()=>{data=null;video.classList.remove('hidden');preview.classList.add('hidden');capture.classList.remove('hidden');retry.classList.add('hidden');confirm.classList.add('hidden');};confirm.onclick=()=>{if(!data)return;close();resolve(data);};cancel.onclick=()=>{close();reject(new Error('La marcación fue cancelada porque la fotografía es obligatoria.'));};}catch(e){close();registrarAlerta({codigo:'FOTO_ERROR',motivo:'No se pudo abrir la cámara: '+(e.message||e),empleado:empleadoActual?.nombre||'Empleado',empleadoId:empleadoActual?.id});reject(new Error('No se pudo abrir la cámara. Autoriza el permiso de cámara e intenta nuevamente.'));}});}
  async function registrarAlerta(data){try{await db().ref('alertas_seguridad').push().set({timestamp:Date.now(),fecha:todayKey(),dispositivoId:deviceId(),navegador:navigator.userAgent||'',...data});}catch(_e){}}
  async function registrarIntentoGps(valid,gps,tipo){try{await db().ref('alertas_gps').push().set({empleadoId:empleadoActual?.id||null,empleado:empleadoActual?.nombre||'Empleado desconocido',tipo:tipo||null,codigo:valid?.codigo||'GPS_BLOQUEADO',motivo:valid?.error||'Intento GPS bloqueado',sedeCercana:valid?.sedeCercana||null,distancia:Number.isFinite(Number(valid?.distancia))?Math.round(Number(valid.distancia)):null,radioPermitido:Number.isFinite(Number(valid?.radio))?Number(valid.radio):null,lat:gps?.lat??null,lon:gps?.lon??null,precisionGps:gps?.accuracy?Math.round(gps.accuracy):null,timestamp:Date.now(),fecha:todayKey(new Date()),dispositivo:navigator.userAgent||'',dispositivoId:deviceId()});}catch(_e){}}
  async function checkSharedDevice(tipo){if(segConfig.alertarDispositivoCompartido===false)return;const id=deviceId(),ref=db().ref('dispositivos_marcacion/'+id),s=await ref.once('value'),last=s.val()||{},windowMs=(Number(segConfig.ventanaDispositivoMinutos)||10)*60000;if(last.empleadoId&&last.empleadoId!==empleadoActual.id&&Date.now()-Number(last.timestamp||0)<=windowMs){await registrarAlerta({codigo:'DISPOSITIVO_COMPARTIDO',motivo:`El mismo dispositivo fue utilizado por ${last.empleado||'otro empleado'} y ${empleadoActual.nombre||'este empleado'} con pocos minutos de diferencia.`,empleado:empleadoActual.nombre||'Empleado',empleadoId:empleadoActual.id,empleadoAnterior:last.empleado||'',empleadoAnteriorId:last.empleadoId||'',tipoMarcacion:tipo});}}
  async function updateDevice(tipo){await db().ref('dispositivos_marcacion/'+deviceId()).set({empleadoId:empleadoActual.id,empleado:empleadoActual.nombre||'Empleado',timestamp:Date.now(),tipoMarcacion:tipo});}
  async function mark(tipo){if(marcando)return;if(!empleadoActual)return msg('Primero ingresa un PIN válido.','error');setBusy(true);msg(gpsConfig.activo?'Verificando ubicación GPS…':'Preparando marcación…');try{const now=new Date(),fecha=todayKey(now),ref=db().ref('marcaciones/'+empleadoActual.id+'/'+fecha),snap=await ref.once('value'),marc=snap.val()||{};let lastEtapa=null,lastTime=0;Object.values(marc).forEach(m=>{if(m&&m.timestamp&&m.timestamp>lastTime){lastTime=m.timestamp;lastEtapa=m.tipo;}});const lastIndex=lastEtapa?etapas.indexOf(lastEtapa):-1;if(lastIndex===-1&&tipo!=='entrada')throw new Error('Debes iniciar con Entrada.');if(lastIndex!==-1&&etapas.indexOf(tipo)!==lastIndex+1)throw new Error('Debes seguir el orden de marcación.');const gps=await getGps(),valid=validarSede(gps);if(!valid.ok){await registrarIntentoGps(valid,gps,tipo);throw new Error(valid.error);}let foto=null;if(requiresPhoto(tipo)){msg('La fotografía es obligatoria para esta marcación.');foto=await capturePhoto();}await checkSharedDevice(tipo);const hora=now.toLocaleTimeString('es-VE'),timestamp=now.getTime();const data={nombre:empleadoActual.nombre||'Empleado',tipo,fecha,hora,timestamp,lat:gps.lat,lon:gps.lon,precisionGps:Math.round(gps.accuracy),gpsVerificado:!!gpsConfig.activo,dispositivoId:deviceId(),evidenciaFotografica:!!foto};if(foto&&segConfig.guardarEvidencia!==false)data.fotoEvidencia=foto;if(valid.sede)Object.assign(data,{sedeId:valid.sede.id,sedeNombre:valid.sede.nombre,sedeDireccion:valid.sede.direccion,distanciaSede:Math.round(valid.distancia),radioPermitido:valid.sede.radio});await ref.child(tipo).set(data);await updateDevice(tipo);const frases={entrada:'¡Buen inicio de jornada!',almuerzo_salida:'Buen provecho',almuerzo_regreso:'Bienvenido de vuelta',salida:'¡Buen trabajo!'},lugar=valid.sede?` · ${valid.sede.nombre} (${Math.round(valid.distancia)} m)`:'';msg(`${empleadoActual.nombre} | ${frases[tipo]} (${hora})${lugar}`,'ok');$('fastPin').value='';setTimeout(()=>{empleadoActual=null;renderEmpleado(null);msg('Marcación guardada. Listo para el próximo empleado.','ok');setBusy(false);},2200);}catch(e){msg(e.message||'No se pudo guardar la marcación.','error');setBusy(false);}}
  function subscribe(){db().ref('configuracion_gps_v51').on('value',s=>{gpsConfig={activo:false,precisionMaxima:120,sedes:{},...(s.val()||{})};});db().ref('configuracion_seguridad_asistencia').on('value',s=>{segConfig={...segConfig,...(s.val()||{})};});}
  ready(()=>{updateClock();setInterval(updateClock,1000);ensureCameraUi();waitFirebase(()=>{subscribe();$('fastPin').addEventListener('input',onPinInput);document.querySelectorAll('#fastButtons button').forEach(b=>b.addEventListener('click',()=>mark(b.dataset.tipo)));msg('Ingrese su PIN para comenzar.');});});
})();
