/* POLADENT v5.0 ENTERPRISE - no modifica Firebase existente */
(function(){
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  let empleados={}, marcaciones={}, justificaciones={}, config={horaEntrada:'08:00',tolerancia:10};
  const today=()=>new Date().toISOString().slice(0,10);
  const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const dbReady=()=>typeof db!=='undefined'&&db&&db.ref;
  function min(h){ if(!h)return 0; const m=String(h).match(/(\d{1,2}):(\d{2})/); return m?(+m[1]*60 + +m[2]):0; }
  function getHora(v){ if(!v)return ''; if(typeof v==='string')return v; return v.hora || v.time || v.fechaHora || ''; }
  function dia(empId,fecha=today()){ return (((marcaciones||{})[empId]||{})[fecha])||{}; }
  function estado(id){ const d=dia(id); if(d.salida) return 'Completo'; if(d.entrada) return 'Presente'; return 'Ausente'; }
  function tarde(id){ const d=dia(id); const h=getHora(d.entrada); if(!h)return false; return min(h)>min(config.horaEntrada)+(Number(config.tolerancia)||0); }
  function horasDia(id){ const d=dia(id); const a=min(getHora(d.entrada)), b=min(getHora(d.salida)); const ls=min(getHora(d.almuerzo_salida)), lr=min(getHora(d.almuerzo_regreso)); if(!a||!b||b<a)return 0; let total=b-a; if(ls&&lr&&lr>ls)total-=lr-ls; return Math.max(0,total/60); }
  function ensure(){
    if($('#pd5Enterprise'))return;
    const panel=$('#adminPanel'); if(!panel)return setTimeout(ensure,400);
    const box=document.createElement('section'); box.id='pd5Enterprise'; box.innerHTML=`
      <div class="pd5-shell"><span class="pd5-badge">⭐ Versión 5.0 Enterprise</span><h2>Centro empresarial Poladent</h2><p>Control ejecutivo, calendario inteligente, perfiles, reportes PDF y respaldo seguro.</p></div>
      <div class="pd5-grid">
        <div class="pd5-card pd5-kpi"><div class="pd5-ico">👥</div><div><span>Empleados</span><strong id="pd5Emp">0</strong></div></div>
        <div class="pd5-card pd5-kpi"><div class="pd5-ico">✅</div><div><span>Presentes hoy</span><strong id="pd5Pres">0</strong></div></div>
        <div class="pd5-card pd5-kpi"><div class="pd5-ico">⚠️</div><div><span>Atrasos</span><strong id="pd5Late">0</strong></div></div>
        <div class="pd5-card pd5-kpi"><div class="pd5-ico">⏱️</div><div><span>Horas hoy</span><strong id="pd5Hours">0</strong></div></div>
      </div>
      <div class="pd5-tabs">
        <button class="pd5-tab active" data-pd5="home">🏠 Dashboard</button><button class="pd5-tab" data-pd5="perfil">👤 Perfil empleado</button><button class="pd5-tab" data-pd5="calendario">📅 Calendario</button><button class="pd5-tab" data-pd5="reportes">📄 Reportes PDF</button><button class="pd5-tab" data-pd5="seguridad">🛡️ Seguridad</button>
      </div>
      <div class="pd5-section active" id="pd5-home"><div class="pd5-two"><div class="pd5-card"><h3>📌 Estado de hoy</h3><div id="pd5Lista" class="pd5-list"></div></div><div class="pd5-card"><h3>🚀 Accesos rápidos</h3><div class="pd5-actions"><button id="pd5ExpHoy">Exportar hoy CSV</button><button id="pd5Print">Imprimir resumen</button><button id="pd5Refresh" class="pd5-btn alt">Actualizar</button></div><br><div class="pd5-note">Consejo: primero revisa presentes, ausentes y atrasos; luego exporta o imprime el resumen para gerencia.</div></div></div></div>
      <div class="pd5-section" id="pd5-perfil"><div class="pd5-card"><h3>👤 Perfil completo del empleado</h3><div class="pd5-form"><select id="pd5EmpSelect"></select><input type="date" id="pd5Desde"><input type="date" id="pd5Hasta"><button id="pd5VerPerfil">Ver perfil</button></div><div id="pd5Perfil"></div></div></div>
      <div class="pd5-section" id="pd5-calendario"><div class="pd5-card"><h3>📅 Calendario inteligente</h3><div class="pd5-form"><input type="date" id="pd5CalFecha"><button id="pd5VerCal">Ver día</button></div><div id="pd5Calendario"></div></div></div>
      <div class="pd5-section" id="pd5-reportes"><div class="pd5-card"><h3>📄 Reporte profesional</h3><div class="pd5-form"><select id="pd5RepEmp"><option value="todos">Todos los empleados</option></select><input type="date" id="pd5RepDesde"><input type="date" id="pd5RepHasta"><button id="pd5Generar">Generar reporte</button></div><div id="pd5Reporte" class="pd5-print"></div></div></div>
      <div class="pd5-section" id="pd5-seguridad"><div class="pd5-card"><h3>🛡️ Seguridad y respaldo</h3><p>Esta versión no cambia la base de datos. Solo lee información y crea reportes.</p><div class="pd5-actions"><button id="pd5Backup" class="pd5-btn good">Descargar respaldo completo JSON</button><button id="pd5Diag" class="pd5-btn alt">Diagnóstico rápido</button></div><div id="pd5SegOut" style="margin-top:12px"></div></div></div>`;
    const first=panel.querySelector('.dashboardHero')||panel.firstElementChild; first ? first.before(box) : panel.prepend(box); bind(); render();
  }
  function bind(){
    $$('.pd5-tab').forEach(b=>b.onclick=()=>{$$('.pd5-tab').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $$('.pd5-section').forEach(x=>x.classList.remove('active')); $('#pd5-'+b.dataset.pd5)?.classList.add('active');});
    $('#pd5Refresh').onclick=render; $('#pd5Print').onclick=()=>window.print(); $('#pd5ExpHoy').onclick=exportHoy; $('#pd5VerPerfil').onclick=renderPerfil; $('#pd5VerCal').onclick=renderCalendario; $('#pd5Generar').onclick=renderReporte; $('#pd5Backup').onclick=backup; $('#pd5Diag').onclick=diag;
    ['pd5Desde','pd5Hasta','pd5RepDesde','pd5RepHasta','pd5CalFecha'].forEach(id=>{const e=$('#'+id); if(e&&!e.value)e.value=today();});
  }
  function fillSelects(){ const opts=Object.entries(empleados).sort((a,b)=>(a[1].nombre||'').localeCompare(b[1].nombre||'')); ['pd5EmpSelect','pd5RepEmp'].forEach(id=>{const s=$('#'+id); if(!s)return; const keep=s.value; s.innerHTML=(id==='pd5RepEmp'?'<option value="todos">Todos los empleados</option>':'')+opts.map(([k,e])=>`<option value="${k}">${esc(e.nombre||'Sin nombre')}</option>`).join(''); if(keep)s.value=keep;});}
  function render(){ if(!$('#pd5Enterprise'))return; fillSelects(); const ids=Object.keys(empleados); const pres=ids.filter(id=>estado(id)!=='Ausente').length; const late=ids.filter(tarde).length; const hours=ids.reduce((a,id)=>a+horasDia(id),0); $('#pd5Emp').textContent=ids.length; $('#pd5Pres').textContent=pres; $('#pd5Late').textContent=late; $('#pd5Hours').textContent=hours.toFixed(1); const lista=$('#pd5Lista'); if(lista) lista.innerHTML=ids.sort((a,b)=>(empleados[a].nombre||'').localeCompare(empleados[b].nombre||'')).map(id=>{const e=empleados[id]||{}, st=estado(id), h=horasDia(id); const cls=st==='Ausente'?'bad':(tarde(id)?'warn':'ok'); return `<div class="pd5-emp"><div class="pd5-emp-left"><div class="pd5-avatar">${e.foto?`<img class="pd5-avatar" src="${e.foto}">`:'👤'}</div><div><b>${esc(e.nombre||'Empleado')}</b><div class="pd5-small">PIN: ${esc(e.pin||'')} · ${h.toFixed(1)} h</div></div></div><span class="pd5-pill ${cls}">${tarde(id)?'Tarde':st}</span></div>`}).join('')||'<p>No hay empleados cargados.</p>'; renderCalendario(false); }
  function rowsFor(id,desde,hasta){ const out=[]; const m=(marcaciones[id]||{}); Object.keys(m).sort().forEach(f=>{ if(f<desde||f>hasta)return; const d=m[f]||{}; out.push({fecha:f,entrada:getHora(d.entrada),almuerzo_salida:getHora(d.almuerzo_salida),almuerzo_regreso:getHora(d.almuerzo_regreso),salida:getHora(d.salida),horas:horasDiaFecha(id,f)});}); return out; }
  function horasDiaFecha(id,fecha){ const old=marcaciones; const d=dia(id,fecha); const a=min(getHora(d.entrada)), b=min(getHora(d.salida)); const ls=min(getHora(d.almuerzo_salida)), lr=min(getHora(d.almuerzo_regreso)); if(!a||!b||b<a)return 0; let total=b-a; if(ls&&lr&&lr>ls)total-=lr-ls; return Math.max(0,total/60); }
  function renderPerfil(){ const id=$('#pd5EmpSelect').value; if(!id)return; const e=empleados[id]||{}, desde=$('#pd5Desde').value||today(), hasta=$('#pd5Hasta').value||today(); const rows=rowsFor(id,desde,hasta); const total=rows.reduce((a,r)=>a+r.horas,0); $('#pd5Perfil').innerHTML=`<div class="pd5-two"><div><h2>${esc(e.nombre||'Empleado')}</h2><p class="pd5-small">PIN: ${esc(e.pin||'')} · Rango ${desde} a ${hasta}</p><h3>Total: ${total.toFixed(2)} horas</h3></div><div>${e.foto?`<img src="${e.foto}" style="width:120px;height:120px;border-radius:28px;object-fit:cover">`:''}</div></div>${table(rows)}`; }
  function table(rows){return `<table class="pd5-table"><thead><tr><th>Fecha</th><th>Entrada</th><th>Almuerzo</th><th>Regreso</th><th>Salida</th><th>Horas</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.fecha}</td><td>${r.entrada||'-'}</td><td>${r.almuerzo_salida||'-'}</td><td>${r.almuerzo_regreso||'-'}</td><td>${r.salida||'-'}</td><td>${r.horas.toFixed(2)}</td></tr>`).join('')||'<tr><td colspan="6">Sin marcaciones en este rango.</td></tr>'}</tbody></table>`}
  function renderCalendario(show=true){ const f=$('#pd5CalFecha')?.value||today(); const out=$('#pd5Calendario'); if(!out)return; const ids=Object.keys(empleados); out.innerHTML=`<table class="pd5-table"><thead><tr><th>Empleado</th><th>Estado</th><th>Entrada</th><th>Salida</th><th>Horas</th></tr></thead><tbody>${ids.map(id=>{const e=empleados[id]||{}, d=dia(id,f), st=d.entrada?(d.salida?'Completo':'Presente'):'Ausente'; const late=d.entrada && min(getHora(d.entrada))>min(config.horaEntrada)+(Number(config.tolerancia)||0); return `<tr><td>${esc(e.nombre||'Empleado')}</td><td><span class="pd5-pill ${st==='Ausente'?'bad':late?'warn':'ok'}">${late?'Tarde':st}</span></td><td>${getHora(d.entrada)||'-'}</td><td>${getHora(d.salida)||'-'}</td><td>${horasDiaFecha(id,f).toFixed(2)}</td></tr>`}).join('')}</tbody></table>`; }
  function renderReporte(){ const id=$('#pd5RepEmp').value, desde=$('#pd5RepDesde').value||today(), hasta=$('#pd5RepHasta').value||today(); let html=`<h2>POLADENT CASA DENTAL</h2><h3>Reporte de asistencia v5.0 Enterprise</h3><p>Desde ${desde} hasta ${hasta}</p>`; const ids=id==='todos'?Object.keys(empleados):[id]; ids.forEach(empId=>{const e=empleados[empId]||{}; const rows=rowsFor(empId,desde,hasta); html+=`<h3>${esc(e.nombre||'Empleado')}</h3>${table(rows)}`;}); html+=`<div class="pd5-watermark">Generado por Poladent Sistema v5.0 Enterprise</div>`; $('#pd5Reporte').innerHTML=html+`<br><button class="pd5-btn" onclick="window.print()">Imprimir / guardar PDF</button>`; }
  function exportHoy(){ const f=today(); const lines=[['Empleado','Estado','Entrada','Salida','Horas']]; Object.keys(empleados).forEach(id=>{const e=empleados[id]||{},d=dia(id,f); lines.push([e.nombre||'',estado(id),getHora(d.entrada),getHora(d.salida),horasDia(id).toFixed(2)]);}); const csv=lines.map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(',')).join('\n'); download(csv,`Poladent_asistencia_hoy_${f}.csv`,'text/csv'); }
  async function backup(){ if(!dbReady())return $('#pd5SegOut').innerHTML='<span class="pd5-pill bad">Firebase no está listo</span>'; const paths=['empleados','marcaciones','feriados_global','dias_libres_empleado','configuracion_v44','roles_v44','justificaciones_v44']; const out={version:'5.0 Enterprise',fecha:new Date().toISOString()}; for(const p of paths){try{out[p]=(await db.ref(p).once('value')).val()||{};}catch(e){out[p]={error:e.message};}} download(JSON.stringify(out,null,2),`Poladent_backup_v5_${today()}.json`,'application/json'); $('#pd5SegOut').innerHTML='<span class="pd5-pill ok">Respaldo descargado</span>'; }
  function diag(){ $('#pd5SegOut').innerHTML=`<div class="pd5-note">Firebase: ${dbReady()?'conectado':'no listo'}<br>Empleados: ${Object.keys(empleados).length}<br>Marcaciones cargadas: ${Object.keys(marcaciones).length}<br>Fecha: ${new Date().toLocaleString()}</div>`; }
  function download(content,name,type){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([content],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href); }
  function subscribe(){ if(!dbReady())return setTimeout(subscribe,500); db.ref('empleados').on('value',s=>{empleados=s.val()||{}; render();}); db.ref('marcaciones').on('value',s=>{marcaciones=s.val()||{}; render();}); db.ref('justificaciones_v44').on('value',s=>{justificaciones=s.val()||{};}); db.ref('configuracion_v44').on('value',s=>{config={...config,...(s.val()||{})}; render();}); }
  document.addEventListener('DOMContentLoaded',()=>{ensure(); subscribe(); const ep=$('#employeePanel')||document.body; const b=document.createElement('div'); b.className='pd5-employee-polish'; b.textContent='Poladent v5.0 Enterprise'; document.body.appendChild(b);});
})();
